###Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [1]:
import numpy as np

In [2]:
c = np.array([1, 2, 3, 3, 1])

print(c)

[1 2 3 3 1]


In [3]:
b = np.array([6, 8, 11, 10, 7])

print(b)

[ 6  8 11 10  7]


In [4]:
a = np.vstack((c, b))

print(a)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [5]:
a_t = a.T

print(a_t)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [6]:
a_mean = a_t.mean(axis = 0)

print(a_mean) 

[2.  8.4]


###Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [7]:
d = a_t - a_mean

print(d)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


###Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [8]:
d1 = d[:, 0]
d2 = d[:, 1]
a_centered_sp = d1 @ d2

print(a_centered_sp)

8.0


In [9]:
N = a_t.shape[0]
N

5

In [10]:
a_centered_sp_1 = a_centered_sp/(N-1)
a_centered_sp_1

2.0

###В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [11]:
np.cov(a_t.T)

array([[1. , 2. ],
       [2. , 4.3]])